// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteUserPaletteEntry(arg1) {
  return window['go']['main']['App']['DeleteUserPaletteEntry'](arg1);
}

export function GetBuiltinPalette() {
  return window['go']['main']['App']['GetBuiltinPalette']();
}

export function GetPalette() {
  return window['go']['main']['App']['GetPalette']();
}

export function GetTransformationSettings() {
  return window['go']['main']['App']['GetTransformationSettings']();
}

export function GetTransformationSettingsPath() {
  return window['go']['main']['App']['GetTransformationSettingsPath']();
}

export function GetUserPalettePath() {
  return window['go']['main']['App']['GetUserPalettePath']();
}

export function ImportThreadFile(arg1) {
  return window['go']['main']['App']['ImportThreadFile'](arg1);
}

export function ImportThreadFilePath(arg1, arg2) {
  return window['go']['main']['App']['ImportThreadFilePath'](arg1, arg2);
}

export function RecalculateThreadCodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecalculateThreadCodes'](arg1, arg2, arg3);
}

export function SaveTransformationSettings(arg1) {
  return window['go']['main']['App']['SaveTransformationSettings'](arg1);
}

export function SaveUserPaletteEntry(arg1) {
  return window['go']['main']['App']['SaveUserPaletteEntry'](arg1);
}
