// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dmc} from '../models';
import {threadcalc} from '../models';

export function DeleteUserPaletteEntry(arg1:string):Promise<Array<dmc.PaletteEntry>>;

export function GetBuiltinPalette():Promise<Array<dmc.PaletteEntry>>;

export function GetPalette():Promise<Array<dmc.PaletteEntry>>;

export function GetTransformationSettings():Promise<threadcalc.TransformationSettings>;

export function GetTransformationSettingsPath():Promise<string>;

export function GetUserPalettePath():Promise<string>;

export function ImportThreadFile(arg1:number):Promise<threadcalc.ImportResult>;

export function ImportThreadFilePath(arg1:string,arg2:number):Promise<threadcalc.ImportResult>;

export function RecalculateThreadCodes(arg1:threadcalc.ImportResult,arg2:Array<threadcalc.CodeCorrection>,arg3:number):Promise<threadcalc.ImportResult>;

export function SaveTransformationSettings(arg1:threadcalc.TransformationSettings):Promise<threadcalc.TransformationSettings>;

export function SaveUserPaletteEntry(arg1:dmc.PaletteEntry):Promise<Array<dmc.PaletteEntry>>;
