// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {threadcalc} from '../models';

export function ImportThreadFile(arg1:number):Promise<threadcalc.ImportResult>;

export function RecalculateThreadCodes(arg1:threadcalc.ImportResult,arg2:Array<threadcalc.CodeCorrection>,arg3:number):Promise<threadcalc.ImportResult>;
